apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: telenor-react-deployment
  labels:
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: telenor-react
        image: apreet/telenor-react
        ports:
        - containerPort: 3000
