---
apiVersion: v1
kind: Service
metadata:
  name: telenor-react
  labels:
    app: app
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
    nodePort: 30080
  selector:
    app: app
---    
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: telenor-react-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: telenor-react
        image: apreet/telenor-react
        ports:
        - containerPort: 3000
---
