apiVersion: apps/v1
kind: Deployment
metadata:
  name: telenor-react-deployment
  labels:
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: telenor-react-deployment 
    spec:
      containers:
      - name: telenor-react
        image: akashpreetngnix:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: service
metadata:
    name: telenor-react-deployment
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: telenor-react-deployment
