apiVersion: apps/v1
kind: Deployment
metadata:
  name: telenor-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telenor-react
  template:
    metadata:
      labels:
        app: telenor-react
    spec:
      containers:
      - name: telenor-react
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: telenor-react
  labels:
     app: telenor-react
spec:
  type: LoadBalancer
  ports:
  - port: 80 
  selector:
     app: telenor-react
